/** MarvelCDB pack names, keyed by pack code. The importer matches the name in parentheses. */
export const PACK_NAMES: Record<string, string> = {
  ant: 'Ant-Man',
  angel: 'Angel',
  aoa: 'Age of Apocalypse',
  aos: 'Agents of S.H.I.E.L.D.',
  bkw: 'Black Widow',
  bp: 'Black Panther',
  cap: 'Captain America',
  core: 'Core Set',
  cw: 'Civil War',
  cyclops: 'Cyclops',
  deadpool: 'Deadpool',
  drax: 'Drax',
  drs: 'Doctor Strange',
  falcon: 'Falcon',
  fne: 'Fear No Evil',
  gam: 'Gamora',
  gambit: 'Gambit',
  gmw: "The Galaxy's Most Wanted",
  gob: 'The Green Goblin',
  hercules: 'Hercules',
  hlk: 'Hulk',
  hood: 'The Hood',
  iceman: 'Iceman',
  ironheart: 'Ironheart',
  jj: 'Jessica Jones',
  jubilee: 'Jubilee',
  luke_cage: 'Luke Cage',
  magneto: 'Magneto',
  mojo: 'Mojo Mania',
  msm: 'Ms. Marvel',
  mts: "The Mad Titan's Shadow",
  mut_gen: 'Mutant Genesis',
  ncrawler: 'Nightcrawler',
  nebu: 'Nebula',
  next_evol: 'NeXt Evolution',
  nova: 'Nova',
  phoenix: 'Phoenix',
  psylocke: 'Psylocke',
  qsv: 'Quicksilver',
  rogue: 'Rogue',
  ron: 'Ronan Modular Set',
  scw: 'Scarlet Witch',
  silk: 'Silk',
  sm: 'Sinister Motives',
  spiderham: 'Spider-Ham',
  spdr: 'SP//dr',
  stld: 'Star-Lord',
  storm: 'Storm',
  synthezoid: 'Synthezoid Smackdown',
  thor: 'Thor',
  toafk: 'The Once and Future Kang',
  trors: 'The Rise of Red Skull',
  tt: 'Trickster Takeover',
  twc: 'The Wrecking Crew',
  valk: 'Valkyrie',
  vision: 'Vision',
  vnm: 'Venom',
  warm: 'War Machine',
  winter: 'Winter Soldier',
  wolv: 'Wolverine',
  wonder_man: 'Wonder Man',
  wsp: 'Wasp',
  x23: 'X-23',
}
